site:
  about:
    siteName: 'Vilnius KUG'
    subtitle: 'Vilnius Kotlin User Group'
    siteDescription: 'Welcome to Kotlin Vilnius meetup group! We are a bunch of friendly Kotlin enthusiasts from all different backgrounds interested in learning Kotlin language which will take over programming world.'
    avatar: '/assets/media/Kotlin_UG_logo.png'
  theme: 'FutureImperfect'
  baseUrl: 'netlify'

theme:
  social:
    twitter: 'vilniuskotlin'
    github: 'Vilnius-KUG'
  menu:
#    - type: 'page'
#      title: 'Home'
#      url: '/'
    - type: "pages"
      atRoot: true
  sidebar:
    - type: recentPosts
      limit: 3
      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'
  legacySearch: false
  metaComponents:
    - type: orchidSearch

services:
  generators:
    externalIndices:
      - 'https://orchid.run/meta/all.index.json'
